# Generated by Django 5.2.2 on 2025-06-08 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("video_file", models.FileField(upload_to="game_videos/")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "game analysis",
                "verbose_name_plural": "game analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "formation_type",
                    models.CharField(
                        choices=[("offense", "Offense"), ("defense", "Defense")], max_length=20
                    ),
                ),
                ("timestamp", models.FloatField()),
                ("confidence_score", models.FloatField()),
                ("player_positions", models.JSONField()),
                ("metadata", models.JSONField(default=dict)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formations",
                        to="analysis.gameanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "formation",
                "verbose_name_plural": "formations",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Play",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "play_type",
                    models.CharField(
                        choices=[("run", "Run"), ("pass", "Pass"), ("special", "Special Teams")],
                        max_length=20,
                    ),
                ),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                ("success_rate", models.FloatField(null=True)),
                ("yards_gained", models.IntegerField(null=True)),
                ("player_routes", models.JSONField()),
                ("metadata", models.JSONField(default=dict)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plays",
                        to="analysis.gameanalysis",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plays",
                        to="analysis.formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "play",
                "verbose_name_plural": "plays",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Situation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("down", models.IntegerField()),
                ("distance", models.IntegerField()),
                ("field_position", models.IntegerField()),
                ("score_differential", models.IntegerField()),
                ("time_remaining", models.IntegerField()),
                ("quarter", models.IntegerField()),
                ("is_red_zone", models.BooleanField(default=False)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situations",
                        to="analysis.gameanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "situation",
                "verbose_name_plural": "situations",
                "ordering": ["time_remaining"],
            },
        ),
    ]
