# Generated by Django 5.2.2 on 2025-06-08 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("video_file", models.FileField(upload_to="analysis_videos/")),
                (
                    "game_version",
                    models.CharField(
                        choices=[("madden_25", "Madden NFL 25"), ("cfb_25", "College Football 25")],
                        max_length=20,
                    ),
                ),
                (
                    "hardware_tier",
                    models.CharField(
                        choices=[
                            ("minimum", "Minimum"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                            ("professional", "Professional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("processing_status", models.CharField(default="pending", max_length=20)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "game analysis",
                "verbose_name_plural": "game analyses",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("timestamp", models.FloatField()),
                ("confidence", models.FloatField()),
                ("player_positions", models.JSONField()),
                ("metadata", models.JSONField(default=dict)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formations",
                        to="api.gameanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "formation",
                "verbose_name_plural": "formations",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Play",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("play_type", models.CharField(max_length=50)),
                ("timestamp", models.FloatField()),
                ("confidence", models.FloatField()),
                ("result", models.JSONField()),
                ("metadata", models.JSONField(default=dict)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plays",
                        to="api.gameanalysis",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plays",
                        to="api.formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "play",
                "verbose_name_plural": "plays",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Situation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.FloatField()),
                ("down", models.IntegerField()),
                ("distance", models.IntegerField()),
                ("field_position", models.IntegerField()),
                ("score_home", models.IntegerField()),
                ("score_away", models.IntegerField()),
                ("quarter", models.IntegerField()),
                ("time_remaining", models.IntegerField()),
                ("metadata", models.JSONField(default=dict)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situations",
                        to="api.gameanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "situation",
                "verbose_name_plural": "situations",
                "ordering": ["timestamp"],
            },
        ),
    ]
